=== 88886/taskAsign/Database/dormsInfo.dtd
<!ELEMENT database (item+)>
        <!ELEMENT item EMPTY>
        <!ATTLIST database NOWID #REQUIRED>
        <!ATTLIST item id #REQUIRED>
        <!ATTLIST item dpt #REQUIRED>
        <!ATTLIST item cls #REQUIRED>
        <!ATTLIST item mbr #REQUIRED>
        <!ATTLIST item ldr #REQUIRED>

=== 88886/taskAsign/Database/dormsInfo.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE database SYSTEM "dormsinfo.dtd">
<database NOWID="436">
    <item id="1" dpt="商学院" cls="13会计1班" mbr="魏敏敏、李文静、赵芮芮、周晓玲" ldr="刘邵岚" />
    <item id="2" dpt="商学院" cls="13会计1班" mbr="陈倩涵、黄芙蓉、王志艳、张巧云" ldr="刘邵岚" />
    <item id="3" dpt="商学院" cls="13会计1班" mbr="张靖、唐瑞玲、宁肖岑、陈茜茜" ldr="刘邵岚" />
    <item id="4" dpt="商学院" cls="13会计1班" mbr="朱叶、汤春、李静洁、陈怡希" ldr="刘邵岚" />
    <item id="5" dpt="商学院" cls="13会计1班" mbr="何丹、张睿、李彩红、刘子骄" ldr="刘邵岚" />
    <item id="6" dpt="商学院" cls="13会计1班" mbr="邹盈、阳兰、罗章玲、王开新" ldr="刘邵岚" />
    <item id="7" dpt="商学院" cls="13会计1班" mbr="刘铭、邓伟、夏洁、向丽云" ldr="刘邵岚" />
    <item id="8" dpt="商学院" cls="13会计1班" mbr="曹焕、祝瑜、熊斌" ldr="刘邵岚" />
    <item id="9" dpt="商学院" cls="13会计1班" mbr="吴琼、王星云、彭晶晶、郑晶晶" ldr="刘邵岚" />
    <item id="10" dpt="商学院" cls="13会计3班" mbr="李思萍、单颖" ldr="刘邵岚" />
    <item id="11" dpt="商学院" cls="13会计1班" mbr="唐艺萌、刘莎莎、阳娇兰、欧思琪" ldr="刘邵岚" />
    <item id="12" dpt="商学院" cls="13会计1班" mbr="赵倩、谢林、王思敏、李妮珍" ldr="刘邵岚" />
    <item id="13" dpt="商学院" cls="13会计2班" mbr="麦景怡、黄露萱、沈泉、龙晶" ldr="刘邵岚" />
    <item id="14" dpt="商学院" cls="13会计2班" mbr="钟梦丽、唐敏丽、李瑶、张婷" ldr="刘邵岚" />
    <item id="15" dpt="商学院" cls="13会计2班" mbr="彭利平、陈子耘、邓静雯、杨婷" ldr="刘邵岚" />
    <item id="16" dpt="商学院" cls="13会计2班" mbr="李超丽、杨习澜、康颖、李娇" ldr="刘邵岚" />
    <item id="17" dpt="商学院" cls="13会计2班" mbr="余素萍、何玉洁、李虹丽、冯莉" ldr="刘邵岚" />
    <item id="18" dpt="商学院" cls="13会计2班" mbr="任昌红、肖艳红、钟秀芳、林润" ldr="刘邵岚" />
    <item id="19" dpt="商学院" cls="13会计2班" mbr="付瑞冰、赵黎蓉、王莉、何红" ldr="刘邵岚" />
    <item id="20" dpt="商学院" cls="13会计2班" mbr="刘玉博、苏欣、邢乐、粟婧" ldr="刘邵岚" />
    <item id="21" dpt="商学院" cls="13会计2班" mbr="廖菡菲、王雨桐、张秀、戴宇" ldr="刘邵岚" />
    <item id="22" dpt="商学院" cls="13会计2班" mbr="旷秋花、刘娇礼、陈嘉玲、常琪" ldr="刘邵岚" />
    <item id="23" dpt="商学院" cls="13会计2班" mbr="王圣瑶、杨思其、李静、彭婷" ldr="刘邵岚" />
    <item id="24" dpt="商学院" cls="13会计3班" mbr="向杨、袁瑞繁、石润雪、陈丽敏" ldr="刘邵岚" />
    <item id="25" dpt="商学院" cls="13会计3班" mbr="邹南妮、王晔、曹巧玲、周碧娴" ldr="刘邵岚" />
    <item id="26" dpt="商学院" cls="13会计3班" mbr="甘冬妮、薛文文、李思敏、贺佳琦" ldr="刘邵岚" />
    <item id="27" dpt="商学院" cls="13会计3班" mbr="王莹、琚乐薇、刘勤、代蔚潇" ldr="刘邵岚" />
    <item id="28" dpt="商学院" cls="13会计3班" mbr="周银、侍念、金科银、魏然" ldr="刘邵岚" />
    <item id="29" dpt="商学院" cls="13会计3班" mbr="唐左今、陆园美、蓝江玲、段丽芬" ldr="刘邵岚" />
    <item id="30" dpt="商学院" cls="13会计3班" mbr="周蜜、卜婧、李瑞丰（13会计3班）、黄雪晴（13会计1班）" ldr="刘邵岚" />
    <item id="31" dpt="商学院" cls="13会计3班" mbr="李宙徽、余颖、蒋怡、姜玲" ldr="刘邵岚" />
    <item id="32" dpt="商学院" cls="13会计3班" mbr="苏明凤、彭倩、周柔倩、李巧霞(休学）" ldr="刘邵岚" />
    <item id="33" dpt="商学院" cls="13会计3班" mbr="琚晶晶、邓慧娟、王亚宁、杨秀玲" ldr="刘邵岚" />
    <item id="34" dpt="商学院" cls="13会计3班" mbr="程兰茜、宁璐、彭婷智、李娟" ldr="刘邵岚" />
    <item id="35" dpt="商学院" cls="13会计4班" mbr="龙文英、李雪、余丽琴、刘晓宇" ldr="刘邵岚" />
    <item id="36" dpt="商学院" cls="13会计4班" mbr="卢俊霞、姜海岸、邹艳红、杜姣" ldr="刘邵岚" />
    <item id="37" dpt="商学院" cls="13会计4班" mbr="白茹、高燕、徐定芳、李芮" ldr="刘邵岚" />
    <item id="38" dpt="商学院" cls="13会计4班" mbr="丁芳、王雅婷、欧阳秀红、李亮" ldr="刘邵岚" />
    <item id="39" dpt="商学院" cls="13会计4班" mbr="邓思威、刘霞红、董爱华、杨宋婷" ldr="刘邵岚" />
    <item id="40" dpt="商学院" cls="13会计4班" mbr="郑露、吴英祯、王丹、韦彩梅" ldr="刘邵岚" />
    <item id="41" dpt="商学院" cls="13会计4班" mbr="姚娜、张红艳、周祺、刘乐" ldr="刘邵岚" />
    <item id="42" dpt="商学院" cls="13会计4班" mbr="欧彩平、钱晶、徐喜妹、黄瑶瑶" ldr="刘邵岚" />
    <item id="43" dpt="商学院" cls="13会计4班" mbr="崔玲玲、张莹、宾婕、陈芳" ldr="刘邵岚" />
    <item id="44" dpt="商学院" cls="13会计4班" mbr="宁添、黄启霞、戴明珠、卿宁静" ldr="刘邵岚" />
    <item id="45" dpt="商学院" cls="13会计4班" mbr="郑园、伍韵峄、王一、刘沛" ldr="刘邵岚" />
    <item id="46" dpt="商学院" cls="13会计4班、13市场营销1班" mbr="郑新颖、肖中超（13会计4班）、廖文雅、卢焱辉（13市场营销）" ldr="刘邵岚" />
    <item id="47" dpt="商学院" cls="13旅管1班" mbr="李佳丽、蔡婷、胡慧、颜亚楠、" ldr="刘邵岚" />
    <item id="48" dpt="商学院" cls="13旅管1班" mbr="鞠馨、刘姣、王韶祯、林奇燕" ldr="刘邵岚" />
    <item id="49" dpt="商学院" cls="13旅管1班" mbr="毛海英、杨小纯、葛睿婕、朱青青" ldr="刘邵岚" />
    <item id="50" dpt="商学院" cls="13旅管1班" mbr="苏寿兰、李秀兰、张燕洁、梁翠兰" ldr="刘邵岚" />
    <item id="51" dpt="商学院" cls="13旅管1班" mbr="李兰、吴瑶、林思含、吴倩" ldr="刘邵岚" />
    <item id="52" dpt="商学院" cls="13旅管1班" mbr="彭鑫、胡东、薛梦洁、李婉意" ldr="刘邵岚" />
    <item id="53" dpt="商学院" cls="13旅管1班" mbr="曹瑞玲、甘蜜、华敏、祝文琴" ldr="刘邵岚" />
    <item id="54" dpt="商学院" cls="13旅管1班" mbr="杨露、刘芳、陈雅丽、刘娴" ldr="刘邵岚" />
    <item id="55" dpt="商学院" cls="13旅管1班" mbr="柳静雯、苏方圆、张珊珊、史新艳" ldr="刘邵岚" />
    <item id="56" dpt="商学院" cls="13旅管1班、13会计1班" mbr="杨舒惠、黄译莹、杨文婷（13级旅管1班）、毛琰莹（13会计1班）" ldr="刘邵岚" />
    <item id="57" dpt="商学院" cls="13旅管2班" mbr="吴雅荣、喻冬慧、覃雅雯、张琼" ldr="刘邵岚" />
    <item id="58" dpt="商学院" cls="13旅管2班" mbr="覃上人、邓丽敏、孙雅丽、樊荣" ldr="刘邵岚" />
    <item id="59" dpt="商学院" cls="13公管1班" mbr="谢金、吉江南" ldr="欧阳斐" />
    <item id="60" dpt="商学院" cls="13旅管2班" mbr="黄玉、戴红娟、谌妮娜、许小敏" ldr="刘邵岚" />
    <item id="61" dpt="商学院" cls="13旅管2班" mbr="张萍、申雪瓶、陈雅兰、周舟" ldr="刘邵岚" />
    <item id="62" dpt="商学院" cls="13旅管2班" mbr="李沙、李晏、任子甜、曾俐" ldr="刘邵岚" />
    <item id="63" dpt="商学院" cls="13旅管2班" mbr="常阳、胡雪玲、曾苹、湛晴" ldr="刘邵岚" />
    <item id="64" dpt="商学院" cls="13旅管2班" mbr="李小玲、周子娣、彭子珈、唐剑萍" ldr="刘邵岚" />
    <item id="65" dpt="商学院" cls="13旅管2班" mbr="吴想、杨兴妹、成爱婷、柏丽莎" ldr="刘邵岚" />
    <item id="66" dpt="商学院" cls="13旅管2班" mbr="喻银莲、王紫娟、陈璇、黄玉娇" ldr="刘邵岚" />
    <item id="67" dpt="商学院" cls="13旅管2班" mbr="李彩虹、伍英、吴小群、谭小芳" ldr="刘邵岚" />
    <item id="68" dpt="商学院" cls="13旅管2班" mbr="彭丽思、李晨、胡钰莹、邓君利" ldr="刘邵岚" />
    <item id="69" dpt="商学院" cls="13旅管2班" mbr="康岳云、向燕、胡静、谢梦萍" ldr="刘邵岚" />
    <item id="70" dpt="商学院" cls="13公管1班" mbr="文丽云、林媛洁、黄敏、龙娇娣" ldr="欧阳斐" />
    <item id="71" dpt="商学院" cls="13公管1班" mbr="赵磊、肖静、李灵、文汶" ldr="欧阳斐" />
    <item id="72" dpt="商学院" cls="13公管1班" mbr="周菁、黄伊汝、钟妤杰、王彬" ldr="欧阳斐" />
    <item id="73" dpt="商学院" cls="13公管1班" mbr="肖卫平、何嘉林、涂薇、杨莹煜" ldr="欧阳斐" />
    <item id="74" dpt="商学院" cls="13公管1班" mbr="冯丽娟、谭璐、明木兰、邓玲慧" ldr="欧阳斐" />
    <item id="75" dpt="商学院" cls="13公管1班" mbr="唐恒露、肖佳西、蔺美芳、张暄" ldr="欧阳斐" />
    <item id="76" dpt="商学院" cls="13公管1班" mbr="刘佩祎、黄博、邓淑清、方意翎" ldr="欧阳斐" />
    <item id="77" dpt="商学院" cls="13公管1班" mbr="杨则琪、姜清、邓思思、林岚" ldr="欧阳斐" />
    <item id="78" dpt="商学院" cls="13公管1班" mbr="汤燕、贺晓菁、乐利兰、范丽慧" ldr="欧阳斐" />
    <item id="79" dpt="商学院" cls="13国贸1班" mbr="李蓉、谢东升、张梦婷、王艳玲" ldr="欧阳斐" />
    <item id="80" dpt="商学院" cls="13国贸1班" mbr="鲁汝婷、杨天虹、吴晓月、杨彩妮" ldr="欧阳斐" />
    <item id="81" dpt="商学院" cls="13国贸1班" mbr="易灿青、胡双双、汤命运、李慧" ldr="欧阳斐" />
    <item id="82" dpt="商学院" cls="13国贸1班" mbr="李璇、胡敏慧、刘恋、王丽容" ldr="欧阳斐" />
    <item id="83" dpt="商学院" cls="13国贸1班" mbr="张秋艳、李丽君、陈佳丽、朱娇彩" ldr="欧阳斐" />
    <item id="84" dpt="商学院" cls="13国贸1班" mbr="王佳尚、李倩莹、蒋思杰、朱春仙" ldr="欧阳斐" />
    <item id="85" dpt="商学院" cls="13国贸1班" mbr="潘妙、朱凤至、彭笑怡、龙静" ldr="欧阳斐" />
    <item id="86" dpt="商学院" cls="13国贸1班" mbr="戴林林、任丹丹、阙巧红、贺凤芝" ldr="欧阳斐" />
    <item id="87" dpt="商学院" cls="13国贸1班" mbr="罗钞、文蓥、黄林、罗云霞" ldr="欧阳斐" />
    <item id="88" dpt="商学院" cls="13国贸1班" mbr="彭水妹" ldr="刘邵岚" />
    <item id="89" dpt="商学院" cls="13国贸1班" mbr="苏继缘、周婷、毛雨娟、康红萍" ldr="欧阳斐" />
    <item id="90" dpt="商学院" cls="13市场营销1班" mbr="李娜、钟婧妮、胡春来、陈晓宇" ldr="欧阳斐" />
    <item id="91" dpt="商学院" cls="13市场营销1班" mbr="谢厅、言婷、刘思驿、王黛琳" ldr="欧阳斐" />
    <item id="92" dpt="商学院" cls="13市场营销1班" mbr="谷剑萍、方盼、陈沛、全珊" ldr="欧阳斐" />
    <item id="93" dpt="商学院" cls="13市场营销1班" mbr="邹芷阳、张书晴、文思语、胡青瑀" ldr="欧阳斐" />
    <item id="94" dpt="商学院" cls="13市场营销1班" mbr="黄静、王莹、白志莉、王倩" ldr="欧阳斐" />
    <item id="95" dpt="商学院" cls="13市场营销1班" mbr="李政、孙柔丽、王景、吴凡" ldr="欧阳斐" />
    <item id="96" dpt="商学院" cls="13市场营销1班" mbr="贺娇、陈洁、陈倩、李玉婷" ldr="欧阳斐" />
    <item id="97" dpt="商学院" cls="13市场营销1班" mbr="段海霞、刘滔、单淑诚、钟家颖、" ldr="欧阳斐" />
    <item id="98" dpt="商学院" cls="13市场营销1班" mbr="张丽萍、江澜、苏明珠、向坤" ldr="欧阳斐" />
    <item id="99" dpt="商学院" cls="13市场营销1班" mbr="刘燕、彭思维、潘思璇、姜倩" ldr="欧阳斐" />
    <item id="100" dpt="商学院" cls="13市场营销1班" mbr="杨拔翠、李井、曾清瑶、武新意" ldr="欧阳斐" />
    <item id="101" dpt="商学院" cls="13会计5班" mbr="陈玲芝、肖婷、龚璇、秦莉" ldr="胡颖" />
    <item id="102" dpt="商学院" cls="13会计5班" mbr="梁佳文、杨亚婷、王奕、赵哚萱" ldr="胡颖" />
    <item id="103" dpt="商学院" cls="13会计5班" mbr="杨华美、伍冰、肖翘楚、刘佳婷" ldr="胡颖" />
    <item id="104" dpt="商学院" cls="13会计5班" mbr="吴杏子、刘姣妮、荣卉、梁莹方" ldr="胡颖" />
    <item id="105" dpt="商学院" cls="13会计5班" mbr="邓露、王迷迷、蔡霞、卜祎蓝" ldr="胡颖" />
    <item id="106" dpt="商学院" cls="13会计5班、13旅管1班、13市场营销1班" mbr="肖渝焱、邓鲜、何成瑶、成文静、" ldr="胡颖" />
    <item id="107" dpt="商学院" cls="13旅管1班" mbr="胡佳洁、梁泽雨、孙洋" ldr="胡颖" />
    <item id="108" dpt="商学院" cls="13公管2班" mbr="赵秋月、傅丽双、刘请波、许雪可" ldr="胡颖" />
    <item id="109" dpt="商学院" cls="13公管2班" mbr="谢爱华、李赛君、汤黎琳、唐怡" ldr="胡颖" />
    <item id="110" dpt="商学院" cls="13公管2班" mbr="邓龙、俞安子、戴小艳、康聪" ldr="胡颖" />
    <item id="111" dpt="商学院" cls="13公管2班" mbr="黄赞、王月晖、雷艳艳、罗鸣城" ldr="胡颖" />
    <item id="112" dpt="商学院" cls="13公管2班、15会计2班" mbr="易胜军、陈茜、杨美丽" ldr="胡颖、邓玉琴" />
    <item id="113" dpt="商学院" cls="15会计1班" mbr="邓颖、刘香、刘淑燕、曾好" ldr="邓玉琴" />
    <item id="114" dpt="商学院" cls="15会计1班" mbr="龚凤、李洪姣、熊佳妮、李惠" ldr="邓玉琴" />
    <item id="115" dpt="商学院" cls="15会计1班" mbr="朱梦伊、刘观美、杨娩玲、易珍" ldr="邓玉琴" />
    <item id="116" dpt="商学院" cls="15会计1班" mbr="陈静、蒋雨萌、田越、姜慧敏" ldr="邓玉琴" />
    <item id="117" dpt="商学院" cls="15会计1班" mbr="罗来燕、刘珊、张洁莹、郭梦丽" ldr="邓玉琴" />
    <item id="118" dpt="商学院" cls="15会计1班" mbr="左美玉、刘思、喻璇、张雨蕾" ldr="邓玉琴" />
    <item id="119" dpt="商学院" cls="15会计1班" mbr="王嘉、王静美、张佳玮、易佳" ldr="邓玉琴" />
    <item id="120" dpt="商学院" cls="15会计1班" mbr="段祺、程乐、乔桢、黄婷" ldr="邓玉琴" />
    <item id="121" dpt="商学院" cls="15会计1班" mbr="彭晓景、彭静、彭思玲、刘婷" ldr="邓玉琴" />
    <item id="122" dpt="商学院" cls="15会计1班" mbr="陈依莎、方诗汝、蒋琳昕、蒋丽" ldr="邓玉琴" />
    <item id="123" dpt="商学院" cls="15会计1班" mbr="丁丽华、谭双艳、刘思娟、李婷婷" ldr="邓玉琴" />
    <item id="124" dpt="商学院" cls="15会计2班" mbr="刘晴、娄梦亭、姚欣霞、罗艺匀" ldr="邓玉琴" />
    <item id="125" dpt="商学院" cls="15会计2班" mbr="沈晚茹、李文洁、王春蕾、何思丽" ldr="邓玉琴" />
    <item id="126" dpt="商学院" cls="15会计2班" mbr="李芳、唐梦莉、朱思玉、王贞珍" ldr="邓玉琴" />
    <item id="127" dpt="商学院" cls="15会计1班" mbr="何幸忆" ldr="邓玉琴" />
    <item id="128" dpt="商学院" cls="15会计2班" mbr="唐艺之、姜佳佳、李敏、余琦" ldr="邓玉琴" />
    <item id="129" dpt="商学院" cls="15会计2班" mbr="杨彬、祝慧、黄春艳、申子怡" ldr="邓玉琴" />
    <item id="130" dpt="商学院" cls="15会计2班" mbr="黄淼、邹敏榕、赵雅琳、陈欢" ldr="邓玉琴" />
    <item id="131" dpt="商学院" cls="15会计2班" mbr="陈静芳、林敏、李琴、黄聪" ldr="邓玉琴" />
